# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: unit-tests
        name: unit tests
        entry: pytest tests/unit/ -v
        language: system
        pass_filenames: false